name: PR Check - Build and Test

on:
  pull_request:
    branches: ["main"] # Trigger on PRs targeting main
  workflow_dispatch: # Allows manual triggering

jobs:
  build_and_test:
    runs-on: ubuntu-22.04
    permissions:
      contents: read # Only need read permission
    name: Build and Test PR
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Configure npm registry settings
        run: |
          cat > .npmrc << EOF
          registry=https://registry.npmjs.org/
          fetch-retries=5
          fetch-retry-factor=5
          fetch-retry-mintimeout=15000
          fetch-retry-maxtimeout=120000
          EOF

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Check required secrets for build
        # Include secrets needed ONLY for the build/test process, not deployment
        run: |
          echo "Checking build secrets..."
          [ -n "${{ secrets.VITE_WEBFLOW_CLIENT_ID }}" ] || (echo "VITE_WEBFLOW_CLIENT_ID secret is missing!" && exit 1)
        env:
          VITE_WEBFLOW_CLIENT_ID: ${{ secrets.VITE_WEBFLOW_CLIENT_ID }}

      - name: Run tests
        run: pnpm exec vitest run
        env:
          NODE_ENV: test
          # Add other necessary test environment variables here

      - name: Build application bundle
        # Build is needed to ensure the code compiles correctly
        run: pnpm build
        env:
          NODE_ENV: production # Use production mode for build consistency
          VITE_WEBFLOW_EXTENSION: true
          USE_GPT_RECOMMENDATIONS: true
          VITE_WEBFLOW_API_KEY: ${{ secrets.VITE_WEBFLOW_API_KEY }} # Needed if build requires it
          VITE_WEBFLOW_SITE_ID: ${{ secrets.VITE_WEBFLOW_SITE_ID }} # Needed if build requires it
          VITE_WEBFLOW_CLIENT_ID: ${{ secrets.VITE_WEBFLOW_CLIENT_ID }}

      - name: Validate build output
        run: |
          if [ ! -d "public" ]; then
            echo "Build output directory (public) is missing"
            exit 1
          fi
          # No need to zip or upload artifact here